services:
  - type: web
    name: inrs-school-erp
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: "school_erp"
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
